<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    //translate
    'Keep me logged in' => 'Ghi nhớ đăng nhập',
    'Can\'t log in?' => 'Quên mật khẩu?',
    'LOG IN' => 'Đăng nhập',
    'Sign Up' => 'Đăng ký',
    'New to G4G? Sign Up' => 'Chưa có tài khoản G4G? Đăng ký.',
    'LBL_REGISTER_MSG' => 'Hãy đăng ký ngay vào cộng đồng G4G để chia sẽ, kết nối, mua bán liên quan đến Game',
    'First name' => 'Tên',
    'Last name' => 'Họ',
    'Your loginname' => 'Tên đăng nhập',
    'Your email' => 'Hộp thư',
    'Password' => 'Mât khẩu',
    'Female' => 'Nữ',
    'Male' => 'Nam',
    'LBL_COPYRIGHT' => '2013 Bản quyền của Công ty OneSoft',
    'LBL_EMPTY_TEXT'=> 'Chưa có nội dung',
    //end translate
    'COM_ERR_INVALID_EMAIL' => 'Địa chỉ email không hợp lệ, vui lòng nhập lại.',
    'COM_ERR_EMAIL_EXISTED' => 'Địa chỉ email đã được đăng ký, vui lòng kiểm tra lại.',
    'COM_ERR_INPUT_REQUIRED' => '"{item}" là trường bắt buộc nhập, vui lòng nhập lại.',
    'COM_ERR_LOGIN_NOT_MATCH' => 'Tên đăng nhập và mật khẩu không khớp, xin vui lòng nhập lại.',
    'COM_REGISTER_SUCCESS' => 'Xin chúc mừng! Bạn đã đăng ký thành công, chúng tôi đã gửi email kích hoạt đến "{item}", xin vui lòng làm theo hướng dẫn để hoàn tất xác nhận thành viên.',
    'COM_REGISTER_ERROR' => 'Cập nhật thông tin thất bại. Vui lòng thử lại!',
    'COM_ERR_RETURNMODELS' => 'Không trả về giá trị của model',
    'COM_ERR_MISS_FIELDS' => 'Bạn phải điền đầy đủ các thông tin.',
    'COM_ERR_LOGINED' => 'Đang có một tài khoản được đăng nhập. Bạn phải thoát trước khi tạo tài khoản mới!',
    'COM_ERR_NOT_ARGEE' => 'Bạn đã không đồng ý tuân thủ quy định của G4G',
    'COM_RESETPASS_SEND_MAIL' => 'Chúng tôi đã gửi email xác nhận đổi mật khẩu đến "{email}", xin vui lòng làm theo hướng dẫn để hoàn tất đổi mật khẩu.',
    'COM_RESETPASS_SUCCESS' => 'Mật khẩu của bạn đã thay đổi thành công.',
    'COM_RESETPASS_ERR_DB' => 'Yêu cầu thay đổi mật khẩu bị gián đoạn. Vui lòng thử lại.',
    'COM_UPDATEEMAIL_SUCCESS' => 'Cập nhật lại email thành công.',
    'COM_ERR_UPDATEEMAIL' => 'Lỗi khi cập nhật lại email.',
    'COM_UPDATEPASS_SUCCESS' => 'Cập nhật lại mật khẩu thành công.',
    'COM_ERR_UPDATEPASS' => 'Lỗi khi cập nhật lại mật khẩu.',
    'COM_UPDATEINFO_SUCCESS' => 'Cập nhật lại thông tin thành công.',
    'COM_ERR_UPDATEINFO' => 'Lỗi khi cập nhật lại thông tin.',
    'COM_ERR_LOGIN_NAME_EXISTED' => 'Tên đăng nhập này đã được đăng ký, vui lòng kiểm tra lại.',
    'COM_ERR_LOGINNAME_EXISTED' => 'Tên đăng nhập này đã được đăng ký, vui lòng kiểm tra lại.',
    'COM_ERR_INVALID_CHAR' => 'Tồn tại ký tự đặc biệt trong "{item}". Ký tự cho phép là a-z,A-Z,_,0-9',
    'COM_ERR_STEP1_MISS_LOCATION' => 'Vui lòng nhập vị trí của bạn.',
    'COM_ERR_STEP1_MISS_GAME' => 'Bạn phải chọn ít nhất một game mà bạn quan tâm.',
    'COM_ERR_NOT_LOGIN' => 'Bạn phải đăng nhập trước.',
    'COM_ERR_BIRTHDAY' => '{item} sinh phải {key} hơn hoặc bằng {value}',
    'COM_ERR_BIRTHDAY_NOT_MATCH' => 'Ngày sinh không đúng định dạng yyyy-MM-dd!',
    'COM_ACTIVATE_USER' => 'Kích hoạt tài khoản thành công.Bạn có thể đăng nhập click vào <a href="{url}">đây</a>',
    'COM_ERR_NOT_ACTIVATE' => 'Không thể kích hoạt tài khoản. Vui lòng liên hệ ban quản trị.',
    'COM_ERR_NOT_MATCH_KEY' => 'Key {action} không phù hợp. Vui lòng theo đường dẫn như trong email đã gửi cho bạn.',
    'COM_ERR_NOTYET_ACTIVATE' => 'Tài khoản chưa kích hoạt. Vui lòng kích hoạt tài khoản trước khi đăng nhập.<br/>Link kích hoạt được gửi vào mail khi đăng ký.',
    'COM_ERR_DELETE_ACCOUNT' => 'Tài khoản đã bị khoá. Vui lòng liên hệ ban quản trị để biết thêm.',
);
