<?php

#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Monday 12th of May 2014 01:51:26 AM

/* !
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
        array(
            "base_url" => Yii::app()->createAbsoluteUrl('user/oauth/'),
            "providers" => array(
                // openid providers
                "Facebook" => array(
                    "enabled" => true,
                    "keys" => array("id" => Yii::app()->params['appfb_id'], "secret" => Yii::app()->params['appfb_secret']),
                    "display" => "popup" // <- this one
                ),
            ),
            // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
            "debug_mode" => false,
            "debug_file" => ""
);
