<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'Are you sure that you want to delete this member?' => 'Bạn muốn xoá tài khoản này?',
    'The default member cannot be removed.' => 'Tài khoản này không thể xoá.',
    'This issue already exists.' => 'Đã tồn tại giá trị này.',
    'Master Products' => 'Danh sách game',
    'List' => 'Danh sách',
);
