<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'COM_ERR_INVALID_EMAIL' => 'Địa chỉ email không hợp lệ, vui lòng nhập lại.',
    'COM_ERR_EMAIL_EXISTED' => 'Địa chỉ email đã được đăng ký, vui lòng kiểm tra lại.',
    'COM_ERR_INPUT_REQUIRED' => '"{item}" là trường bắt buộc nhập, vui lòng nhập lại.',
    'COM_ERR_LOGIN_NOT_MATCH' => 'Tên đăng nhập và mật khẩu không khớp, xin vui lòng nhập lại.',
    'COM_REGISTER_SUCCESS' => 'Xin chúc mừng! Bạn đã đăng ký thành công, chúng tôi đã gửi email kích hoạt đến "{email}", xin vui lòng làm theo hướng dẫn để hoàn tất xác nhận thành viên.',
    'COM_REGISTER_ERROR' => 'Đăng ký thất bại. Vui lòng thử lại!',
    'COM_ERR_RETURNMODELS' => 'Không trả về giá trị của model',
    'COM_ERR_MISS_FIELDS' => 'Bạn phải điền đầy đủ các thông tin.',
    'COM_ERR_LOGINED' => 'Đang có một tài khoản được đăng nhập. Bạn phải thoát trước khi tạo tài khoản mới!',
    'COM_ERR_NOT_ARGEE' => 'Bạn đã không đồng ý tuân thủ quy định của G4G',
    'COM_RESETPASS_SEND_MAIL' => 'Chúng tôi đã gửi email xác nhận đổi mật khẩu đến "{email}", xin vui lòng làm theo hướng dẫn để hoàn tất đổi mật khẩu.',
    'COM_RESETPASS_SUCCESS' => 'Mật khẩu của bạn đã thay đổi thành công.',
    'COM_RESETPASS_ERR_DB' => 'Yêu cầu thay đổi mật khẩu bị gián đoạn. Vui lòng thử lại.',
    'COM_UPDATEEMAIL_SUCCESS' => 'Cập nhật lại email thành công.',
    'COM_ERR_UPDATEEMAIL' => 'Lỗi khi cập nhật lại email.',
    'COM_UPDATEPASS_SUCCESS' => 'Cập nhật lại mật khẩu thành công.',
    'COM_ERR_UPDATEPASS' => 'Lỗi khi cập nhật lại mật khẩu.',
    'COM_UPDATEINFO_SUCCESS' => 'Cập nhật lại thông tin thành công.',
    'COM_ERR_UPDATEINFO' => 'Lỗi khi cập nhật lại thông tin.',
    'COM_ERR_LOGIN_NAME_EXISTED' => 'Tên đăng nhập này đã được đăng ký, vui lòng kiểm tra lại.',
);
